### ISSUE TITLE
[Add Webradio]: voices radio

### ISSUE THREAD

**Issue by tacacho** [jcorporation/webradiodb#1019]
### Webradio Name

Voices Radio

### Stream URI

https://voicesradio.out.airtime.pro/voicesradio_a

### Genres

Club,Underground,Live

### Homepage

https://www.voicesradio.co.uk/

### Image

https://www.voicesradio.co.uk/voices.svg

### Country

United Kingdom

### Region

London

### Language

English

### Codec

MP3

### Bitrate

128

**Comment by tacacho** [comment]
It seems like there is some bug with the image. Perhaps because it is an svg?
![image](https://github.com/user-attachments/assets/61a97049-ca11-4803-bd4b-ee37d834cf38)

**Comment by jcorporation** [comment]
I Concept the Images with imagemagick to the correct format in the pipeline. SVG and ICO have sometimes issues. You can convert it manually and add it to a modify issue.
