### ISSUE TITLE
[Add Webradio]: the lot radio (this one is a video and audio stream but i think it's the only one they offer. I hope it works!)

### ISSUE THREAD

**Issue by tacacho** [jcorporation/webradiodb#1056]
### Webradio Name

The Lot Radio

### Stream URI

https://playback.livepeer.studio/hls/85c28sa2o8wppm58/index.m3u8

### Genres

Club,House,Rock

### Homepage

https://www.thelotradio.com/

### Image

https://play-lh.googleusercontent.com/Fjbaj5EjZrd0n3dLPT-do9j4rpt4aapi0msad-oXG2K4cQQvLTBB6ioLOiiBVZU3pXEI=s0?imgmax=0

### Country

USA

### Region

New York City

### Language

English

### Description

Expect a continuous stream of the best and most varied music New York City has to offer.

**Comment by jcorporation** [comment]
ffprobe works, let's try it.
