### ISSUE TITLE
[Modify Webradio]: Coldstar Radio

### ISSUE THREAD

**Issue by artur-shaik** [jcorporation/webradiodb#1080]
### Webradio to modify

https://ice.coldstar.online/high.ogg

### Note

Changed radio stream audio format

### New webradio Name

Coldstar Radio

### New stream URI

https://ice.coldstar.online/high.mp3

### New genres

Trance,Progressive,Psy,House,Deep House,Deep Tech

### New homepage

https://coldstar.online/

### Image

https___ice_coldstar_online_high_ogg.webp

### New country

Kyrgyzstan

### New language

English

### New codec

MP3

### New bitrate

256

**Comment by jcorporation** [comment]
Why this change?
