### ISSUE TITLE
[Add Webradio]: Maus Radio

### ISSUE THREAD

**Issue by georgkrause** [jcorporation/webradiodb#1122]
### Webradio Name

Maus Radio

### Stream URI

https://wdr.de/wdrlive/media/diemaus.m3u

### Genres

Kids

### Homepage

https://www.wdrmaus.de/hoeren/

### Image

https://www.wdrmaus.de/icon/apple-icon-120x120.png

### Country

Germany

### Region

North Rhine-Westphalia

### Language

German

### Codec

MP3

### Bitrate

128

**Comment by georgkrause** [comment]
Thanks @jcorporation ! Is there a way to update the DB?

**Comment by jcorporation** [comment]
The database is automatically updated each morning, german time.

```
Currently there are 655 stations in the database and the last update was on 10/11/2024, 6:29:32 AM.
```
