### ISSUE TITLE
Get Playlist returns error 404

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/webradiodb#185]
When trying to click on "Get Playlist" on any webradio listed in https://jcorporation.github.io/webradiodb/ , a 404 error is always returned.

![image](https://user-images.githubusercontent.com/4215150/148663030-d4c4c07f-b842-47fa-82d2-b1156f37d8f1.png)

![image](https://user-images.githubusercontent.com/4215150/148662817-b0aed4aa-e96f-4da4-bd48-f56562bf708e.png)

**Comment by jcorporation** [comment]
Thanks for reporting this bug. Is now fixed.
