### ISSUE TITLE
[Add Webradio]: Radio Paradise Rock Mix FLAC

### ISSUE THREAD

**Issue by tblegen** [jcorporation/webradiodb#438]
### Webradio Name

Radio Paradise Rock Mix FLAC

### Stream URI

https://stream.radioparadise.com/rock-flac

### Genres

rock

### Homepage

https://radioparadise.com/

### Image

https://radioparadise.com/apple-touch-icon.png

### Country

The United States Of America

### Language

american english

### Codec

FLAC

### Bitrate

1441

**Comment by jcorporation** [comment]
The station already exists. You should add alternate streams.
