### ISSUE TITLE
[Modify Webradio]: Rock Radio Belgrade (Рок Радио Београд)

### ISSUE THREAD

**Issue by nidzo80** [jcorporation/webradiodb#462]
### Webradio to modify

https://mastermedia.shoutca.st/proxy/rockradio?mp=/stream

### Note

Stream changed name. It is now AS FM Rock stream.
Old Rock Radio Belgrade has new stream address I have added as new.

### New webradio Name

AS FM Rock stream

### New stream URI

https://mastermedia.shoutca.st/proxy/rockradio?mp=/stream

### New genres

Rock

### New homepage

https://radioas.fm/strimovi/

### New country

Serbia

**Comment by jcorporation** [comment]
You changed the "Webradio to modify" Entry. Merging this is not possible, please add the link to the original webradio entry here in the comments and I fix it for you.

**Comment by jcorporation** [comment]
No response
