### ISSUE TITLE
[Modify Webradio]: Hirschmilch Electronic

### ISSUE THREAD

**Issue by opengk** [jcorporation/webradiodb#463]
### Webradio to modify

http://hirschmilch.de:7000/electronic.mp3

### Note

Modified logo. The former one was not fitting well (length vs width) and overzoomed. The proposed logo is for the electronic radio at Hirschmilch. Moreover there are other channels/radios from hirschmilch, and we could add all with their own logo.

### New webradio Name

Hirschmilch Electronic

### New stream URI

http://hirschmilch.de:7000/electronic.mp3

### New genres

Techno

### New homepage

https://hirschmilch.de/

### Image

https://hirschmilch.de/images/newsicons/electronic.png

### New country

Germany

### New language

English

### New codec

MP3

### New bitrate

128

### New description

Since it's launch at the end of 2008 hirschmilch.de brings you free electronic music 24/7.

**Comment by opengk** [comment]
Thanks Jürgen !

Just a question. When or how does it apply into mympd ? Do I have to do some action ?

Schöne Grüsse aus Elsass !

**Comment by jcorporation** [comment]
The webradioDB is rebuild nightly and myMPD caches the database one day.
