### ISSUE TITLE
[Add Webradio]: ballermann-radio (F) this from today's visit to site

### ISSUE THREAD

**Issue by Noitarud** [jcorporation/webradiodb#472]
### Webradio Name

Megapark Radio

### Stream URI

https://megapark.stream24.net/radio-megapark.mp3

### Genres

Music

### Homepage

https://www.ballermann-radio.de/

### Country

Germany

### Language

German

**Comment by jcorporation** [comment]
Why 4 requests for one webradio?

**Comment by Noitarud** [comment]
A is the primary
B Your input engine does not support option for multiple bitrates, this is a higher rate which gives listener more quality (I wrote the different bitrate in the title)
C mirror of A maybe (I did not check IP address)
D they changed it to broadcast E, maybe a mirror now
E and F the same providor offers other stations besides the primary station, these are independent of the first three and play different music from each other and first three.

**Comment by jcorporation** [comment]
There is a issue template to add a webradio and a separate template to add alternative streams with other codecs/bitrates. You should use this.
