### ISSUE TITLE
RauteMusik (Germany)

### ISSUE THREAD

**Issue by Noitarud** [jcorporation/webradiodb#474]
Appears to be https://www.rm.fm/ now, site appears to host fifty. This is the selection i have kept.
<P><a href="http://90s-high.rautemusik.fm"><B>Raute90s</B></a></P>
<P><a href="http://charthits-high.rautemusik.fm"><B>#Musik.ChartHits</B></a></P>
<P><a href="http://club-high.rautemusik.fm"><B>#Musik.Club</B></a></P>
<P><a href="http://harder-high.rautemusik.fm"><B>#Musik.HardeR</B></a></P>
<P><a href="http://house-high.rautemusik.fm"><B>#Musik.House(funky)</B></a></P>
<P><a href="http://rock-high.rautemusik.fm"><B>#Musik.Rock(extreme)</B></a></P>
<P><a href="http://trance-high.rautemusik.fm"><B>#Musik.Trance</B></a></P>
<P><a href="http://techhouse-high.rautemusik.fm"><B>#Musik.TechHouse(progressive)</p>

**Comment by jcorporation** [comment]
What do you expect I should do with this info?

**Comment by Noitarud** [comment]
See #475

**Comment by Noitarud** [comment]
Instead of diving you should be able to use a tool like cports.exe (free, Nir Sofer /Nir Soft) to diagnose what your computer has connected to while you are listening.

- And if you are, you can also do http://m.cnr.cn/#/pages/broadcast/broadcast as well, there are several Chinese ones there in the scripts that I've never retrieved.

**Comment by jcorporation** [comment]
#473

**Comment by Noitarud** [comment]
Browser "Monocles" lets you see enough from its "requests" menu option. Works on both domains.
