### ISSUE TITLE
WeaReoNe

### ISSUE THREAD

**Issue by Noitarud** [jcorporation/webradiodb#475]
Organisation (not sure of parent name) has a number of stations, here are three:

<P><a href="http://listen.technobase.fm/tunein-aacplus-pls"><B>TechnoBase.FM-AACplus 96k</B></a></P>
<P><a href="http://listen.technobase.fm/tunein-dsl-pls"><B>TechnoBase.FM-MP3 192k</B></a></P>
<P><a href="http://listen.technobase.fm/tunein-aacisdn-pls"><B>TechnoBase.FM-AACplus 40k</B></a></P>

<P><a href="http://listen.trancebase.fm/tunein-aacplus-pls"><B>TranceBase.FM-AACplus 96k</B></a></P>
<P><a href="http://listen.trancebase.fm/tunein-dsl-pls"><B>TranceBase.FM-MP3 192k</B></a></P>
<P><a href="http://listen.trancebase.fm/tunein-aacisdn-pls"><B>TranceBase.FM-AACplus 40k</B></a></P>

<P><a href="http://listen.housetime.fm/tunein-aacplus-pls"><B>HouseTime.FM-AACplus 96k</B></a></P>
<P><a href="http://listen.housetime.fm/tunein-dsl-pls"><B>HouseTime.FM-MP3 192k</B></a></P>
<P><a href="http://listen.housetime.fm/tunein-aacisdn-pls"><B>HouseTime.FM-AACplus 40k</B></a></P>

But page here hosts all urls:
https://www.technobase.fm/streamlinks

**Comment by jcorporation** [comment]
What do you expect I should do with this info?

**Comment by Noitarud** [comment]
This is a list of radio station URLs, clicking any of the bold ones will show browser player to which you press play to listen.

You were asking for more stations to include in your service, right, I had so many it was tedious to do one a time, if this is tedious for you you could view the HTML of this page (and the other) and use a script to extract the names and addresses, else right click and copy link and paste whereever.

**Comment by Noitarud** [comment]
After reading your comment on (F) I realise you are unfamiliar with multiple bit rates and the possibility that one providor can offer many stations. This is my list of three stations from that one providor with three different bitrates I offer for each. If you visit that last URL you see even more stations and more than three bitrates on each.

**Comment by jcorporation** [comment]
#473

**Comment by Noitarud** [comment]
I think you meant #472;
You seem to have ignored purpose of A, E, F these were unique stations, then I do what you said in #472 for B, C. But I think I will drop the idea of filling your forms, too tedious and may not be accepted.
Perhaps you can offer a mass addition input, permit comma/tab/semicomma delimited tables for example.
