### ISSUE TITLE
[Add Webradio]: бард

### ISSUE THREAD

**Issue by grayenot** [jcorporation/webradiodb#480]
### Webradio Name

Бард-Радио Bard-Radio

### Stream URI

https://listen.myrh.ru/Bard-Radio

### Genres

авторская песня

### Homepage

https://www.bard-radio.net/

### Image

https://bard-radio.ru/wp-content/uploads/2023/02/bardradio-2017-logo5-big-300x300.jpg

### Country

The Russian Federation

### Language

russian

### Codec

MP3

### Bitrate

128

### Description

Интернет-радио авторской песни

**Comment by jcorporation** [comment]
Homepage shows an certificate error.
