### ISSUE TITLE
[Add Webradio]: 

### ISSUE THREAD

**Issue by cycler01** [jcorporation/webradiodb#511]
### Webradio Name

Ράδιον (Radhion)

### Stream URI

 	http://cycler.mywire.org:25222/stream

### Genres

Electronica,Pop,Rock,Chill,Trip-Hop,Various

### Homepage

https://tsoukias.eu/wordpress/internet-radio/

### Image

https://tsoukias.eu/wordpress/wp-content/uploads/2023/02/Radhion_Logo_4-283x300.png

### Country

Greece

### Language

English, Greek

### Codec

MP3

### Bitrate

128

### Description

A personal amateur radio based on liquidsoap that plays a wide variety of music

**Comment by jcorporation** [comment]
Seems to be not legal?!

**Comment by cycler01** [comment]
Not legal in what sense?
It is not a business, and I try to get a cheap Intellectual property permit
for broadcast from my country's agencies. The cheapest one is 50 euros per
month! Can you imagine! I will try to get something cheaper...

Theodore
