### ISSUE TITLE
[Add Webradio]: LRT Radijas

### ISSUE THREAD

**Issue by Kass401** [jcorporation/webradiodb#558]
### Webradio Name

LRT Radijas

### Stream URI

https://radijas.lrt.lt/radijas/stream04/streamPlaylist.m3u8

### Genres

Various,News,Music,Talk

### Homepage

https://www.lrt.lt/mediateka/tiesiogiai/lrt-radijas

### Image

https://upload.wikimedia.org/wikipedia/commons/a/a1/LRT_Radijas_Logo_2022.svg

### Country

Lithuania

### Language

Lithuanian

### Codec

AAC

**Comment by ShitfacedKass** [comment]
Master playlist: https://7123988bd0a14cca8a92f4a47f9cfe1a.dlvr1.net/radijas/master.m3u8
