### ISSUE TITLE
[Add Webradio]: LRT Klasika

### ISSUE THREAD

**Issue by Kass401** [jcorporation/webradiodb#559]
### Webradio Name

LRT Klasika

### Stream URI

https://stream-live.lrt.lt/klasika/stream04/streamPlaylist.m3u8

### Genres

Classical, Talk, Culture

### Homepage

https://www.lrt.lt/mediateka/tiesiogiai/lrt-klasika

### Image

https://upload.wikimedia.org/wikipedia/commons/5/5d/LRT_Klasika_Logo_2022.svg

### Country

Lithuania

### Language

Lithuanian

### Codec

AAC

**Comment by ShitfacedKass** [comment]
Master playlist: https://7123988bd0a14cca8a92f4a47f9cfe1a.dlvr1.net/klasika/master.m3u8
