### ISSUE TITLE
[Add Webradio]: LRT Opus

### ISSUE THREAD

**Issue by Kass401** [jcorporation/webradiodb#560]
### Webradio Name

LRT Opus

### Stream URI

https://radijas.lrt.lt/opus/stream04/streamPlaylist.m3u8

### Genres

Modern, Contemporary, Alternative, Indie

### Homepage

https://www.lrt.lt/mediateka/tiesiogiai/lrt-opus

### Image

https://upload.wikimedia.org/wikipedia/commons/e/e4/LRT_Opus_Logo_2022.svg

### Country

Lithuania

### Language

Lithuanian

### Codec

AAC

**Comment by ShitfacedKass** [comment]
Master playlist: https://7123988bd0a14cca8a92f4a47f9cfe1a.dlvr1.net/opus/master.m3u8
