### ISSUE TITLE
[Add Webradio]: Rádio Melodia 97.5 FM

### ISSUE THREAD

**Issue by goliv04053** [jcorporation/webradiodb#682]
### Webradio Name

Rádio Melodia 97.5 FM

### Stream URI

https://24483.live.streamtheworld.com/MELODIAFMAAC.aac

### Genres

gospel, music

### Homepage

https://melodia.com.br/player/

### Image

https://melodia.com.br/player/img/capa_MELODIA_192.png

### Country

Brazil

### Language

Brazilian Portuguese

### Codec

AAC

### Bitrate

32

### Description

A voz que fala ao coração!

**Comment by jcorporation** [comment]
Not reachable?

**Comment by goliv04053** [comment]
Not reachable?

**Comment by goliv04053** [comment]
@jcorporation 
Tested the stream. It's working for me. I do not know if this is Brazil geo locked only. It doesn't make sense if it is. Strange

**Comment by jcorporation** [comment]
Even the link to the image does not work from here.

**Comment by goliv04053** [comment]
> Even the link to the image does not work from here.

https://github.com/jcorporation/webradiodb/assets/22873288/ee01b18e-f44f-4e00-887f-f150af124f23

This video is a test without VPN. Then, i tested with a VPN (Windscribe) connected to the USA (as an testing example). The website doesn't even load. Very strange indeed. I recorded a video showing that it's working for Brazilians here. I don't know if it   can still be added because of this problems. I found an alternative stream link. Do you wanna to test it?

https://playerservices.streamtheworld.com/api/livestream-redirect/MELODIAFMAAC.aac

@jcorporation

**Comment by jcorporation** [comment]
It work now. It seems it was a temporary problem.
