### ISSUE TITLE
[Add Webradio]: CGTN Radio

### ISSUE THREAD

**Issue by goliv04053** [jcorporation/webradiodb#701]
### Webradio Name

CGTN Radio

### Stream URI

https://sk.cri.cn/am846.m3u8

### Genres

talk, news

### Homepage

https://radio.cgtn.com

### Image

https://radio-res.cgtn.com/image/2112/1639986367791.jpg

### Country

China

### Language

English

### Codec

ADTS

### Bitrate

32

### Description

CGTN Radio

**Comment by jcorporation** [comment]
Duplicate: China Plus (China Radio International) - English
