### ISSUE TITLE
[Modify Webradio]: Must FM

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/webradiodb#78]
### Webradio to modify

https://stream.rcs.revma.com/cm96zpmrmm0uv

### New webradio Name

Must FM

### New stream URI

https://stream.rcs.revma.com/cm96zpmrmm0uv

### New genres

Pop-Rock

### New homepage

https://mustfm.be/

### Image

https://user-images.githubusercontent.com/4215150/147934092-900ec0fc-a3cd-4e4f-93c3-9ed5c66dd147.png

### New country

Belgium

### New language

French

### New description

Must FM est une station de radio à caractère provincial Belgique, dans le Brabant Wallon.

**Comment by tsunulukai** [comment]
Fix Wrong picture

**Comment by jcorporation** [comment]
You can use the new note field to describe the change.
