### ISSUE TITLE
[Add Webradio]: La Vaina Hits

### ISSUE THREAD

**Issue by chokofreshmix** [jcorporation/webradiodb#872]
### Webradio Name

La Vaina Hits

### Stream URI

https://chokostream.com:8050/live

### Genres

Urbana

### Homepage

https://lavainahits.net/

### Image

https://lavainahits.net/logo.png

### Country

Republica Dominicana

### State

San Pedro De Macoris

### Language

español

### Codec

AAC

### Bitrate

128

### Description

Detonando Hits!

**Comment by chokofreshmix** [comment]
[jcorporation](https://github.com/jcorporation) When will it be reflected in the app?

**Comment by jcorporation** [comment]
After the next index creation. This process runs each night.
