### ISSUE TITLE
[Add alternate stream for webradio]: LRT Opus

### ISSUE THREAD

**Issue by Kass401** [jcorporation/webradiodb#892]
### Webradio to modify

https://radijas.lrt.lt/opus/stream04/streamPlaylist.m3u8

### Stream URI

https://stream-live.lrt.lt/opus/stream04/streamPlaylist.m3u8

### Codec

HLS

### Bitrate

192

**Comment by jcorporation** [comment]
Original URI does not work anymore, replacing the URI is better then adding a new uri.
