### ISSUE TITLE
[Add Webradio]: BBC Radio 4

### ISSUE THREAD

**Issue by rodajc** [jcorporation/webradiodb#965]
### Webradio Name

BBC Radio 4

### Stream URI

https://as-hls-ww.live.cf.md.bbci.co.uk/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u8

### Genres

current affairs, politics, talk & speech, science, debate, drama

### Homepage

https://www.bbc.co.uk/sounds/play/live:bbc_radio_fourfm

### Image

https://imgur.com/OCqneDN

### Country

UK

### Language

English

### Codec

AAC

### Bitrate

96 kb/s

### Description

Radio 4 broadcasts a wide variety of spoken-word programmes from the BBC's headquarters at Broadcasting House, London.

**Comment by jcorporation** [comment]
Already in the database

**Comment by rodajc** [comment]
Yes. It is. Can't get it to play in android Open Radio app though.

**Comment by jcorporation** [comment]
This is no reason to add it again. If a stream does not work you can use the modify link to suggest new stream uri. However the last check of this stream reports it working.

**Comment by rodajc** [comment]
Sorry. My apologies. Noob mistake.

BTW, I solved my problem by switching from Open Radio app to RadioDroid app in android.
