### ISSUE TITLE
Classical California KUSC

### ISSUE THREAD

**Issue by mayanez** [jcorporation/webradiodb#982]
### Webradio Name

Classical California KUSC

### Stream URI

https://27223.live.streamtheworld.com:443/KUSCMP256_SC

### Genres

Classical

### Homepage

https://www.kusc.org/

### Image

https://www.kusc.org/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F8usdt07j8s00%2F4dYCDL0d4UDkSBLTYUeSd2%2F11cb881aba59be91feb2d6bb357ef23d%2Fkusc-color.png&w=1920&q=75

### Country

United States

### Region

California

### Language

English

### Codec

MP3

### Bitrate

256

### Description

Listener Supported Classical Music Radio Station in Southern California

**Comment by mayanez** [comment]
They have additional redundant servers on their `.pls` file. Not sure how those are usually handled.

Here's the link with their stream links: https://www.kusc.org/articles/what-is-the-direct-link-to-a-stream-kusc

**Comment by jcorporation** [comment]
After the radio was added, you can add alternative streams.
